# Generated by Django 2.2.7 on 2020-07-14 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delegate',
        ),
        migrations.DeleteModel(
            name='LipaNaMpesa',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
