# Generated by Django 2.2.7 on 2020-07-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200714_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='google_event_id',
        ),
        migrations.RemoveField(
            model_name='program',
            name='venue',
        ),
        migrations.AddField(
            model_name='program',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='role',
            field=models.CharField(blank=True, help_text='eg <em>CEO Google</em>.', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='summitday',
            name='day_number',
            field=models.CharField(blank=True, choices=[('1', 'ONE'), ('2', 'TWO')], max_length=5, null=True),
        ),
    ]
