# Generated by Django 2.2.7 on 2020-07-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200717_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='meeting_link',
            field=models.URLField(default='google.com'),
            preserve_default=False,
        ),
    ]
