# Generated by Django 2.2.7 on 2020-07-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200717_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='website',
            field=models.URLField(default='https://google.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
