# Generated by Django 2.2.7 on 2020-07-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200722_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='venue',
            field=models.CharField(default='Online', max_length=30),
        ),
    ]
