# Generated by Django 2.2.7 on 2020-07-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_program_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='category',
            field=models.CharField(blank=True, choices=[('major', 'Major'), ('minor', 'Minor')], default='MN', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='category',
            field=models.CharField(blank=True, choices=[('major', 'Major'), ('minor', 'Minor')], default='MN', max_length=5, null=True),
        ),
    ]
