# Generated by Django 2.2.7 on 2020-08-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200722_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='category',
            field=models.CharField(blank=True, choices=[('major', 'Major'), ('middle', 'Middle'), ('minor', 'Minor')], default='MN', max_length=6, null=True),
        ),
    ]
